level3/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get :favorites, on: :member
    get :follows, on: :member
    get :followers, on: :member
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
  end

  root 'books#profile'
  get 'mypage' => 'books#profile'
  # get 'users/index' => 'users#index'
  # get 'users/show' => 'users#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

level3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Level3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<!-- ヘッダー -->
<header>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Bookers!</a>
      </div>
      
      <div class="collapse navbar-collapse" id="navbarEexample1">
        <ul class="nav navbar-nav navbar-right">      
          <% if user_signed_in? %>
              <li class="user_name">Logged in as <%= current_user.name %></li>
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "Users", users_path %></li>
              <li><%= link_to "Books", books_path %></li>
              <li><%= link_to "LogOut", destroy_user_session_path,method: :delete %></li>
          <% else %>
              <li><%= link_to "新規登録", new_user_registration_path %></li>
              <li><%= link_to "ログイン", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>
 <!--ヘッダー-->

    <%= yield %>
  </body>
</html>