level3/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get :favorites, on: :member
    get :follows, on: :member
    get :followers, on: :member
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
  end

  root 'books#profile'
  get 'mypage' => 'books#profile'
  # get 'users/index' => 'users#index'
  # get 'users/show' => 'users#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

level3/app/models/book.rb
class Book < ApplicationRecord
  validates :opinion, length: { maximum: 200 }
  belongs_to :user
  has_many :favorites, dependent: :destroy

  def favorited_by? user
  	favorites.where(user_id: user.id).exists?
  end

end

level3/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  # GET /books
  # GET /books.json
  def index
    @book = Book.new
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  def profile
    @book = Book.new
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    @book.user_id = current_user.id

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :opinion, :user_id)
    end

    def correct_user
    book = Book.find(params[:id])
    if current_user.id != book.user.id
      redirect_to root_path
    end
  end
end

level3/app/helpers/books_helper.rb
module BooksHelper
end

level3/app/views/books/_form.html.erb
<%= form_for(book) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :opinion %>
    <%= f.text_area :opinion %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

level3/app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

level3/app/views/books/index.html.erb
<p id="notice"><%= notice %></p>


<div class="container">
  <div class="row">
    <div class="col-sm-3">
      <h3>User info</h3>

      <% if current_user.image? %>
      　<%=  image_tag(current_user.image.url, :class => "icon_img") %>
    　<% else %>
      　<%= image_tag "画像がありません" %>
      <% end %>
    
      <table class="table">
        <thead>
          <tr>
            <th>name</th>      
            <th>introduction</th>
          </tr>
        </thead>
        <tbody>
          <td><%= current_user.name %></td>
          <td>説明</td>
        </tbody>
      </table>
      <%= link_to 'User edit', edit_user_registration_path %>

     <h3>New Books</h3>
     <%= render 'form', book: @book %>
    </div>

    <div class="col-sm-9">
      <h1>Books</h1>

      <table class="table table-striped">
        <thead>
          <tr>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.opinion %></td>
              <td id="favorite-btn-<%= book.id %>"><%= render 'favorites/favorite', book: book %></td>
              <% if current_user.id == book.user_id %>
                <td><%= link_to 'Edit', edit_book_path(book) %></td>
                <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% else %>
              <td> </td>
              <td> </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>
   </div>
  </div>
</div>

level3/app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

level3/app/views/books/profile.html.erb
<p id="notice"><%= notice %></p>


<div class="container">
  <div class="row">
    <div class="col-sm-3">
      <h3>User info</h3>

      <% if current_user.image? %>
      　<%=  image_tag(current_user.image.url, :class => "icon_img") %>
    　<% else %>
      　<%= image_tag "画像がありません" %>
      <% end %>
    
      <table class="table">
        <thead>
          <tr>
            <th>name</th>      
            <th>introduction</th>
          </tr>
        </thead>
        <tbody>
          <td><%= current_user.name %></td>
          <td>説明</td>
        </tbody>
      </table>
      投稿数:<%= current_user.books.count %><br>
      いいね数：<%= current_user.favorites.count %><br>
      <%= link_to 'User edit', edit_user_registration_path %>

     <h3>New Books</h3>
     <%= render 'form', book: @book %>
    </div>

    <div class="col-sm-9">
      <h1>My Books</h1>

      <table class="table table-striped">
        <thead>
          <tr>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
        <tr>
        <% current_user.books.each do |book| %>
					<td><%= book.title %></td>
          <td><%= link_to book.title, book_path(book) %></td>
              <% if current_user.id == book.user_id %>
                <td><%= link_to 'Edit', edit_book_path(book) %></td>
                <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% else %>
	              <td> </td>
	              <td> </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>
   </div>
  </div>
</div>

level3/app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Opinion:</strong>
  <%= @book.opinion %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>