level3/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get :favorites, on: :member
    get :follows, on: :member
    get :followers, on: :member
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
  end

  root 'books#profile'
  get 'mypage' => 'books#profile'
  # get 'users/index' => 'users#index'
  # get 'users/show' => 'users#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

level3/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true, uniqueness: true 
  validates :name, length: { minimum: 2, maximum: 10 }
  mount_uploader :image, ImageUploader
  has_many :books
  has_many :favorites, dependent: :destroy
  has_many :active_relationships, class_name:'Relationship', foreign_key: :following_id
  has_many :passive_relationships, class_name:'Relationship',foreign_key: :followed_id
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    # フォローされているユーザーの中から引数に渡されたユーザーがいるかどうかを調べる
    passive_relationships.find_by(following_id: user.id).present?
  end

end

level3/app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

level3/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

level3/app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

level3/app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

level3/app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

level3/app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

level3/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
    @book = Book.new

  end

  def show
  	@user = User.find(params[:id])
    @book = Book.new
  end

  def favorites
  	@user = User.find(params[:id])
  end

  # フォローしているユーザー一覧を表示するためのアクション
  def follows
   @user = User.find(params[:id])
   @follows = @user.followings
  end

  # フォロワー一覧を表示するためのアクション
  def followers
   @user = User.find(params[:id])
   @followers = @user.followers
  end

end

level3/app/helpers/users_helper.rb
module UsersHelper
end

level3/app/views/users/favorites.html.erb
<h2>いいね一覧</h2>


<!--         <h4 class="user">
            <span class="user-email">
              <%#= link_to book.user.email, user_path(book.user) %>
            </span>
        <span class="user-id"><%#= post.user.email %></span>
        </h4>
        <div class="book-body">
            <%#= book.opinion %> -->
        <!-- </div> -->

    <table class="table table-striped">
        <thead>
          <tr>
            <th>title</th>
            <th>opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
            <% if @user.favorites.empty? %>
                <div class="list-group-item">
                  まだお気に入りされた投稿はありません。
                </div>
            <% end %>
            <% @user.favorites.map { |f| f.book }.each do |book| %>
            <tr>
                <td><%= book.title %></td>
                <td><%= book.opinion %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

level3/app/views/users/followers.html.erb
<table>
  <% @followers.each do |user|  %>
    <tr>
      <td>email : <%= user.email %></td>
      <td>
        <% if current_user != user %>
          <% if @user.followed_by?(current_user) %>
            <%= link_to "following",user_relationships_path(user),method: :delete %>
          <% else %>
            <%= link_to "follow",user_relationships_path(user),method: :post %>
          <% end %>
        <% end%>
      </td>
    </tr> 
  <% end %>
</table>

level3/app/views/users/follows.html.erb
<table>
  
  <% @follows.each do |user| %>
    <tr>
      <td>email : <%= user.email %></td>
      <td>
        <% if current_user != user %>
          <% if @user.followed_by?(current_user) %>
            <%= link_to "following",user_relationships_path(user),method: :delete %>
          <% else %>
            <%= link_to "follow",user_relationships_path(user),method: :post %>
          <% end %>
        <% end%>
      </td>
    </tr>
  <% end %>
</table>

level3/app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-3">
      <h3>User info</h3>

      <% if current_user.image? %>
      　<%=  image_tag(current_user.image.url, :class => "icon_img") %>
    　<% else %>
      　<%= image_tag "画像がありません" %>
      <% end %>
    
      <table class="table">
        <thead>
          <tr>
            <th>name</th>      
            <th>introduction</th>
          </tr>
        </thead>
        <tbody>
          <td><%= current_user.name %></td>
          <td>説明</td>
        </tbody>
      </table>
      <%= link_to 'User edit', edit_user_registration_path %>

     <h3>New Books</h3>
     <%= render 'books/form', book: @book %>
    </div>

    <div class="col-sm-9">
      <h1>Users</h1>

      <table class="table table-striped">
        <thead>
          <tr>
          	<th>  </th>
            <th>UserName</th>
            <th>Mail</th>
            <th>いいね</th>
            <th>フォロー</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
        	<% @users.each do |user| %>
            <tr>
            	<td>      
            		<% if user.image? %>
      　						<%=  image_tag(user.image.url, :class => "icon_img") %>
								<% else %>
      　						<%= image_tag "画像がありません" %>
      					<% end %>
				      </td>
            	<td><%= link_to user.name, user_path(user.id) %></td>
            	<td><%= user.email %></td>
              <td><%= link_to "いいね一覧", favorites_user_path(user.id) %></td>
              <td>
                <% if current_user != user %>
                  <% if user.followed_by?(current_user) %>
                    <%= link_to "follow解除",user_relationships_path(user),method: :delete %>
                  <% else %>
                    <%= link_to "followする",user_relationships_path(user),method: :post %>
                  <% end %>
                <% end%>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
   </div>
  </div>
</div>

level3/app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-3">
      <h3>User info</h3>

      <% if current_user.image? %>
      　<%=  image_tag(current_user.image.url, :class => "icon_img") %>
    　<% else %>
      　<%= image_tag "画像がありません" %>
      <% end %>
    <%= link_to 'follows', follows_user_path(@user)%>

    <%= link_to 'followers', followers_user_path(@user)%>
      <table class="table">
        <thead>
          <tr>
            <th>name</th>      
            <th>introduction</th>
            <th>フォロー</th>
          </tr>
        </thead>
        <tbody>
          <td><%= current_user.name %></td>
          <td>説明</td>
          <td>
            <% if current_user != @user %>
              <% if @user.followed_by?(current_user) %>
                <%= link_to "follow解除", user_relationships_path(@user), method: :delete %>
              <% else %>
                <%= link_to "followする", user_relationships_path(@user), method: :post %>
              <% end %>
            <% end %>
          </td>
        </tbody>
      </table>
      <%= link_to 'User edit', edit_user_registration_path %>

     <h3>New Books</h3>
     <%= render 'books/form', book: @book %>
    </div>

    <div class="col-sm-9">
      <h1>Books</h1>

      <table class="table table-striped">
        <thead>
          <tr>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
        	<% @user.books.each do |book| %>
            <tr>
	            <td><%= book.title %></td>
	            <td><%= book.opinion %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
   </div>
  </div>
</div>